# [START django_app]
runtime: python38
instance_class: B1

handlers:
# This configures Google App Engine to serve the files in the app's static
# directory.
- url: /static
  static_dir: static/

# This handler routes all requests not caught above to your main app. It is
# required when static routes are defined, but can be omitted (along with
# the entire handlers section) when there are no static files defined.
- url: /.*
  script: auto
# [END django_app]

- url: /bootstrap
  static_dir: bootstrap

basic_scaling:
  max_instances: 2
  idle_timeout: 10m

env_variables:
  DB_NAME: "main"
  DB_PASSWORD: "Vpkdg]jogd,55"
  DB_USER: "thong-gae"
  DB_CONNECT_NAME: "/cloudsql/my-django-gae-304810:asia-southeast1:myapp-django"


