# Generated by Django 3.1.6 on 2021-02-18 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210218_0727'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_position', to='myapp.position'),
        ),
    ]
