# Generated by Django 3.1.6 on 2021-02-18 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_division_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_employee', to='myapp.employee'),
        ),
    ]
