# Generated by Django 3.1.6 on 2021-02-18 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_division_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='division',
        ),
        migrations.AddField(
            model_name='employee',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_division', to='myapp.division'),
        ),
    ]
