# Generated by Django 3.1.6 on 2021-02-18 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20210218_0934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='division',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='division',
            name='job',
        ),
        migrations.RemoveField(
            model_name='position',
            name='department',
        ),
        migrations.RemoveField(
            model_name='position',
            name='job',
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_position', to='myapp.position'),
        ),
        migrations.AddField(
            model_name='position',
            name='position',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
