# Generated by Django 3.1.6 on 2021-02-19 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_position_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airforce_rank', models.CharField(max_length=6)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='lucky_number',
            field=models.CharField(blank=True, default=None, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='passport',
            field=models.CharField(blank=True, default=None, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='still_service',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='visa',
            field=models.CharField(blank=True, default=None, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='telephone',
            field=models.CharField(blank=True, help_text='fill 10 number', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rank', to='myapp.rank'),
        ),
    ]
