# Generated by Django 3.1.6 on 2021-02-19 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20210219_0716'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icao_code', models.CharField(max_length=4)),
                ('city', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('runway_length', models.IntegerField()),
                ('runway_direction', models.CharField(max_length=30)),
                ('update', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='update',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(help_text='duration in minute')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arivals', to='myapp.airport')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='myapp.airport')),
            ],
        ),
    ]
