# Generated by Django 3.1.6 on 2021-02-19 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20210219_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='update',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
