# Generated by Django 3.1.6 on 2021-02-19 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20210219_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='airforce_rank',
            field=models.CharField(max_length=10),
        ),
    ]
