# Generated by Django 3.1.6 on 2021-02-19 01:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20210219_0843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airport',
            name='create_at',
        ),
        migrations.AlterField(
            model_name='airport',
            name='update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
