# Generated by Django 3.1.6 on 2021-02-19 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_auto_20210219_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='airport',
            name='update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
