# Generated by Django 3.1.6 on 2021-02-19 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_auto_20210219_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='rank',
            name='airforce_rank',
            field=models.CharField(max_length=20),
        ),
    ]
