# Generated by Django 3.1.6 on 2021-02-21 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_auto_20210219_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_picture', to='myapp.division'),
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_image', models.ImageField(upload_to='image/')),
                ('employee', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='employee_picture', to='myapp.employee')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
