# Generated by Django 3.1.6 on 2021-03-06 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_auto_20210303_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_pilot',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
