# Generated by Django 3.1.6 on 2021-03-07 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_auto_20210307_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='afaps',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
