# Generated by Django 3.1.6 on 2021-03-09 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_employee_position_other'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_birth',
            field=models.DateField(blank=True, default=None, help_text='ปี ค.ศ. / เดือน / วัน', null=True),
        ),
    ]
