# Generated by Django 3.1.6 on 2021-03-23 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_auto_20210309_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_birth',
            field=models.DateField(blank=True, default=None, help_text='ปี ค.ศ. / เดือน / วัน (ตัวอย่าง 1990-09-01)', null=True),
        ),
        migrations.CreateModel(
            name='Lessonlearn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.TextField()),
                ('date_fly', models.DateTimeField(null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('update', models.DateTimeField(auto_now=True, null=True)),
                ('employee', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='employee_Lessonlearn', to='myapp.employee')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
