# Generated by Django 3.1.6 on 2021-03-23 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_auto_20210323_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonlearn',
            name='airport',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='airport_Lessonlearn', to='myapp.airport'),
        ),
    ]
