# Generated by Django 3.1.7 on 2021-03-28 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_lessonlearn_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonlearn',
            name='mission',
            field=models.CharField(choices=[('1', 'Domestic'), ('2', 'International')], default='Domestic', max_length=20),
        ),
    ]
