# Generated by Django 3.1.7 on 2021-04-09 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_auto_20210409_2009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('first_name_thai', 'last_name_thai')},
        ),
    ]
