# Generated by Django 3.1.7 on 2021-04-09 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0040_auto_20210409_2024'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='picture',
            unique_together={('employee_image',)},
        ),
    ]
