# Generated by Django 3.1.7 on 2021-04-19 00:24

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0043_auto_20210418_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(default=None, upload_to='image/', validators=[myapp.models.validate_image], verbose_name='Image'),
        ),
    ]
