# Generated by Django 3.1.7 on 2021-04-23 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0044_employee_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='is_pilot',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='still_service',
            field=models.BooleanField(default=False),
        ),
    ]
